server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery: # 服务发现，openFeign会应用到,否则无法被server-a调用到
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: SEATA_GROUP
    alibaba:
      seata:
        tx-service-group: seata_stu_wei_wang
  application:
    name: seata-stu-b
  jpa:
    show-sql: true

seata: # seata配置中心
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      application: seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP

  config: # 配置中心
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      dataId: seataServer.properties
  enabled: true
  tx-service-group: seata_stu_wei_wang
  service:
    vgroupMapping:
      seata_stu_wei_wang: default
  enable-auto-data-source-proxy: true





